In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [6]:
array = np.array([1,2,3,4,5]) # 1차원 배열 만들기
print(array)

[1 2 3 4 5]


In [7]:
print("배열의 자료형:", array.dtype) # 배열의 자료형 반환

배열의 자료형: int64


In [10]:
matrix = np.array([[1,2,3], [4,5,6]]) # 2행 3열의 배열 생성 (메트릭스)
print(matrix)

[[1 2 3]
 [4 5 6]]


In [11]:
# 그 외 matrix data EDA 하는법
print("배열의 크기:", matrix.size)
print("배열의 형태:", matrix.shape)
print("배열의 차원", matrix.ndim)

배열의 크기: 6
배열의 형태: (2, 3)
배열의 차원 2


In [12]:
# 배열의 연산 (이 연산 기능을 매우 빠르게함)
print("배열의 합:", np.sum(matrix))
print("배열의 평균:", np.mean(matrix))
print("배열의 최대값:", np.max(matrix))
print("배열의 최소값:", np.min(matrix))

배열의 합: 21
배열의 평균: 3.5
배열의 최대값: 6
배열의 최소값: 1


In [13]:
# 배열 형태 바꾸기 reshape
reshaped_matrix = matrix.reshape(3,2)
print(reshaped_matrix)

[[1 2]
 [3 4]
 [5 6]]


In [14]:
# 배열의 전치 T
transposed = matrix.T
print("전치된 배열:", transposed)   # (2,3) --> (3,2) 행과 열이 바뀌는걸 전치라 함

전치된 배열: [[1 4]
 [2 5]
 [3 6]]


In [15]:
# python print 

print("apple", "banana", "strawberry", sep=",") #공백을 ","로 채움

apple,banana,strawberry


In [16]:
print("hello", end="") # 줄바꿈없이 출력
print("World")

helloWorld


In [19]:
# f-string
Age = 25
Name = 'Minsu'
print(f"이름: {Name}, 나이: {Age}") 

이름: Minsu, 나이: 25


In [23]:
# 줄바꿈                  귀찮으니까 여기 더 적겠음 \t --> tab
print("첫번째\n두번째")

첫번째
두번째


In [24]:
import pandas as pd
import numpy as np

In [27]:
# Series 생성  --> 1차원 데이터 구조, 인덱스를 함께 저장

data = [10,20,30,40]
series = pd.Series(data)
print("Series:\n", series)

Series:
 0    10
1    20
2    30
3    40
dtype: int64


In [28]:
# 인덱스 series 호출
print("첫 번째 값", series[0])

첫 번째 값 10


In [49]:
# 딕셔너리를 사용해 DataFrame 생성
data = {"이름" : ["김철수","이영희","박민수"],
        "수학" : [85,90,79],
        "영어" : [88,84,95]}
df = pd.DataFrame(data)
print("DataFrame:\n", df)

DataFrame:
     이름  수학  영어
0  김철수  85  88
1  이영희  90  84
2  박민수  79  95


In [50]:
print(df)

    이름  수학  영어
0  김철수  85  88
1  이영희  90  84
2  박민수  79  95


In [51]:
df # 데이터프레임으로 출력 (표형식)

,이름,수학,영어
0,김철수,85,88
1,이영희,90,84
2,박민수,79,95


In [52]:
fruits = ["apple", "banana", "cherry"]
numbers = [1, 2, 3, 4, 5]
print(type(fruits)) # (class ’list')

<class 'list'>


In [55]:
print(fruits[0]) # apple (첫 번째 요소)
print(fruits[-1]) # cherry (마지막 요소)

apple
cherry


In [60]:
fruits.append("orange") # 요소 추가
print(fruits) # ['apple’, banana', 'cherry, ‘orange]
fruits.remove("banana") # 특정 _오소 삭제
print(fruits) # [‘apple’, cherry‘, ‘orange]

['apple', 'banana', 'cherry', 'orange']
['apple', 'cherry', 'orange']


In [65]:
# 튜블 (tuple)
colors = ( "red" , "green" , "blue" )
print(colors[1]) # green
# colors[1] = "yellow“ # 오류 발생 (튜플은 변경 불가)

green


In [71]:
person = {"name": "Alice", "age" : 25, "city": "Seoul"}
print(person["name"]) # Alice
person["age"] = 26 # 값 변경
print(person) # {'name'Alice', 'age'： 26, city： 'Seoul'}

Alice
{'name': 'Alice', 'age': 26, 'city': 'Seoul'}


In [72]:
# 집합(set)
numbers = {1, 2, 3, 4, 4, 5}
print(numbers) # //, 2, 3. 4, 5} (중복 제거)

{1, 2, 3, 4, 5}
